<!DOCTYPE html>
<html lang="pt-br">
<head>
		<meta charset="UTF-8">
		<title>Dashboard | Trabalho Alemanha</title>
    <link rel="icon" href=""/>
		<meta name="author" content="jeconiass2009@hotmail.com, +55 (84)9 9438-1350"/>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <meta name="description" content="Descripton here!"/>
    <meta name="keywords" content="Your keywords here!"/>
    <meta name="URL" content="<?=empty($_SERVER['HTTPS']) ? 'http://'.$_SERVER['SERVER_NAME'] : 'https://' . $_SERVER['SERVER_NAME'];?>"/>
    <meta name="language" content="portuguese"/>
    <meta name="copyright" content="all rights"/>
    <meta name="robots" content="INDEX, FOLLOW"/>
    <meta name="revisit-after" content="3 days"/> <!-- days that you revise your content -->
    <meta name="reply-to" content="youremail@yourwebsite.com.br"/>
    <meta name="document-rights" content="Public"/>
    <meta name="document-rating" content="General"/>
    <meta name="document-state" content="Dynamic"/>
    <meta http-equiv="Content-Language" content="PT-BR"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"> <!-- essential to mobile experience -->

    <!-- CSS -->
    <link rel="stylesheet" href="<?= PATH.'/resources/assets/css/bootstrap.min.css'?>">
    <link rel="stylesheet" href="<?= PATH.'/resources/assets/css/page.dashboard.css'?>">
    <link rel="stylesheet" href="<?= PATH.'/resources/assets/css/dataTable.bootstrap4.min.css'?>">
    <link rel="stylesheet" href="<?= PATH.'/resources/assets/css/page.empresas.css'?>">
    <link rel="stylesheet" href="<?= PATH.'/resources/assets/css/font-awesome.min.css'?>">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css">
    <link rel="stylesheet" href="<?= PATH.'/resources/assets/css/animate.css'?>">
</head>
<!-- Modal -->
	<div class="modal fade" id="modal_confirmacao" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog  modal-md" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Remover Serviço</h4>
				</div>
				<div class="modal-body">
					<h1 style="color: #373737; font-size: 1.3em;">Você realmente deseja remover <strong id="name-servico-remove"></strong>?</h1>
					<p style="font-size: 0.8em; color: #373737; font-weight: 700;">Se você fizer isso, não será possível recuperar nenhuma informação!</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
					<button type="button" class="btn btn-danger" id="btn-remove-servico">Sim</button>
				</div>
			</div>
		</div>
	</div>
<!-- Modal -->
	<div class="modal fade" id="modal_detalhes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog modal-lg" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel">Detalhamento</h4>
				</div>
				<div id="progress-bar" style="width:0; height: 2px; background-color: #009543; text-align: center;"></div>
				<div class="modal-body">
					<div class="row" id="row-modal">
						<div class="col-md-2 div-modal-img">
								<img id="change-img" src="" alt="imagem do servico">
								<p id="img-size">150x150</p>
						</div>
						<div class="col-md-3">
							<div class="col-md-12">
								<label for="load_servico">Serviço</label>
								<input type="text" name="load_servico" id="load_servico" class="form-control" value="">
							</div>
							<div class="col-md-12">
								<label for="load_localidade">Localidade</label>
								<input type="text" name="load_localidade" id="load_localidade" class="form-control" value="">
							</div>
						</div>
						<div class="col-md-3">
							<div class="col-md-12">
								<label for="load_tipo">Tipo</label>
								<select class="form-control" name="load_tipo" id="load_tipo" required>
									<option value="Full Time">Full Time</option>
									<option value="Part Time">Part Time</option>
									<option value="Free Lancer">Free Lancer</option>
								</select>
							</div>
							<div class="col-md-12">
								<label for="load_salario">Salário</label>
								<input type="text" name="load_salario" id="load_salario" class="form-control" value="">
							</div>
						</div>
						<div class="col-md-3 offset-md-1">
							<div class="col-md-12">
								<label for="load_habilidades">Habilidades</label>
								<input type="text" name="load_habilidades" id="load_habilidades" class="form-control" value="">
							</div>
							<div class="col-md-12">
								<label for="load_categoria">Categoria</label>
								<select class="form-control" name="load_categoria" id="load_categoria" required>
									<option value=""></option>
									<?php
									$count_categorias = count($categorias);
									$a = 0;
									while ($a < $count_categorias) {
										echo '<option value="'.$categorias[$a]['categoria_value'].'">'.$categorias[$a]['categoria_name'].'</option>';
										$a++;
									}
									 ?>
								</select>
							</div>
						</div>
						<div class="col-md-12">
							<label for="load_descricao">Descrição</label>
							<textarea name="load_descricao" id="load_descricao" class="form-control" rows="10" style="resize: none;" placeholder="Escreva algo aqui..."></textarea>
						</div>
						<div class="">
							<input type="file" name="logotipo" id="logotipo" value="" accept="image/png, image/jpeg, image/jpg">
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
					<button type="button" class="btn btn-primary" id="edit_servico">Salvar</button>
				</div>
			</div>
		</div>
	</div>
  <body>
    <div class="container">
      <div class="row">
        <?php
          require($_SERVER['DOCUMENT_ROOT'].PATH.'/resources/views/company/aside/menu.company.php');
         ?>
        <section class="col-md-10 body-section">
            <?php
              require($_SERVER['DOCUMENT_ROOT'].PATH.'/resources/views/company/aside/topbar.company.php');
             ?>
            <section id="" class='col-md-12 section'>
              <article class="article-generic">
                <h1 class="h1-article">Informações do Serviço</h1>
                  <form class="row" id="form-service" method="post">
                    <div class="col-md-6">
                      <label for="servico">Cargo</label>
                      <input type="text" id="servico" class="form-control" name="servico" value="" placeholder="Developer Web" autocomplete="off" required>
                    </div>
										<div class="col-md-6">
                      <label for="categoria">Categoria</label>
											<select class="form-control" name="categoria" id="categoria" required>
												<option value=""></option>
												<?php
												$count_categoria = count($categorias);
												$a = 0;
												while ($a < $count_categoria) {
													echo '<option value="'.$categorias[$a]['categoria_value'].'">'.$categorias[$a]['categoria_name'].'</option>';
													$a++;
												}
												 ?>
											</select>
                    </div>
                    <div class="col-md-6">
                      <label for="local">Localidade</label>
                      <input type="text" id="local" class="form-control" name="local" value="" placeholder="Germany, Berlim" autocomplete="off" required>
                    </div>
                    <div class="col-md-6">
                      <label for="duracao1">Duração</label>
                      <div class="row">
												<div class="col-md-2" style="padding: 0;">
													<input type="text" id="duracao1" class="form-control" name="duracao1" value="" placeholder="2-3" autocomplete="off">
	                      </div>
												<div class="col-md-10" style="padding-right: 0;">
												 	<select class="form-control" id="duracao2" name="duracao2">
														<option value="" disabled selected>meses, anos</option>
														<option value="anos">Ano(s)</option>
														<option value="meses">Mes(es)</option>
												 	</select>
												</div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <label for="tipo">Tipo</label>
											<select class="form-control" name="tipo" id="tipo" required>
												<option value=""></option>
												<option value="Full Time">Full Time</option>
												<option value="Part Time">Part Time</option>
												<option value="Free Lancer">Free Lancer</option>
											</select>
                    </div>
                    <div class="col-md-6">
                      <label for="salario">Salário</label>
                      <input type="text" id="salario" class="form-control" name="salario" value="" placeholder="€ 4,250.00" autocomplete="off" required>
                    </div>
                    <div class="col-md-6">
                      <label for="habilidades">Habilidades</label>
                      <input type="text" id="habilidades" class="form-control" name="habilidades" value="" placeholder="PHP, MySQL, HTML" autocomplete="off" required>
                    </div>
										<div class="col-md-6">
                      <label for="empresa">Empresa</label>
											<select class="form-control" name="empresa" id="empresa" required>
												<option value=""></option>
												<?php
												$count_empresas = count($empresas);
												$a = 0;
												while ($a < $count_empresas) {
													echo '<option value="'.$empresas[$a]['id'].'">'.$empresas[$a]['nome'].'</option>';
													$a++;
												}
												 ?>
											</select>
                    </div>
										<div class="col-md-12">
											<label for="descricao">Descrição</label>
											<textarea name="descricao" id="descricao" class="form-control" rows="10" style="resize: none;" placeholder="Escreva algo aqui..."></textarea>
										</div>
                    <div class="col-md-3 offset-md-9">
                      <label for="">Verifique os dados antes de salvar</label>
                      <input type="submit" id="salvar" class="form-control btn btn-primary" name="salvar" value="Registrar">
                    </div>
                  </form>
              </article>
              <article class="article-generic">
                <h1 class="h1-article">Serviços Registrados</h1>
                  <div class="table-responsive">
                    <table id="table_servicos" class="table table-striped table-bordered">
                      <thead>
                        <tr>
													<th>Empresa</th>
                          <th width="20%">Serviço</th>
                          <th width="15%">Localidade</th>
                          <th width="15%">Tipo</th>
                          <th width="15%">Ação</th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php
                        $count_dados = count($servicos);
                        $a = 0;
                        while ($a < $count_dados) {
													$color = '#363636';
													if ($servicos[$a]['status'] == 0) {
														$color = '#C0172C';
													}
                          echo '
                          <tr>
														<td>'.$servicos[$a]['nome'].'</td>
                            <td>'.$servicos[$a]['servico'].'</td>
                            <td>'.$servicos[$a]['local'].'</td>
                            <td>'.$servicos[$a]['tipo'].'</td>
                            <td class="td-action" data-id="'.$servicos[$a]['id'].'"><i class="fa fa-eye" data-name="read" aria-hidden="true" title="Ver/Editar"></i><i class="fa fa-ban" aria-hidden="true" data-name="bloquear" title="bloquear" style="color: '.$color.'"></i><i class="fa fa-trash" aria-hidden="true" data-name="remove" title="Remover"></i></td>
                          </tr>';
                          $a++;
                        }
                         ?>
                      </tbody>
                    </table>
                  </div>
              </article>
            </section>
        </section>
      </div>
    </div>
  </body>
    <script src="<?= PATH.'/resources/assets/js/jquery.min.js'?>"></script>
		<script src="<?= PATH.'/resources/assets/js/tether.min.js'?>"></script>
		<script src="<?= PATH.'/resources/assets/js/bootstrap.min.js'?>"></script>
    <script src="<?= PATH.'/resources/assets/js/page.dashboard.js'?>"></script>
    <script src="<?= PATH.'/resources/assets/js/jquery.dataTable.min.js'?>"></script>
    <script src="<?= PATH.'/resources/assets/js/dataTable.bootstrap4.min.js'?>"></script>
    <script src="<?= PATH.'/resources/assets/js/notify.min.js'?>"></script>
    <script src="<?= PATH.'/resources/assets/js/maskMoney.js'?>"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>
    <script src="<?= PATH.'/resources/assets/js/page.servicos.js'?>"></script>
</html>
